In [1]:
# Load libraries
from sklearn.ensemble import AdaBoostClassifier
from sklearn import datasets
# Import train_test_split function
from sklearn.model_selection import train_test_split
#Import scikit-learn metrics module for accuracy calculation
from sklearn import metrics

In [2]:
# Load data
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [3]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3) # 70% training and 30% test

In [4]:
# Create adaboost classifer object
abc = AdaBoostClassifier(n_estimators=50,learning_rate=1)
# Train Adaboost Classifer
model = abc.fit(X_train, y_train)
#Predict the response for test dataset
y_pred = model.predict(X_test)

In [5]:
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))


Accuracy: 0.9555555555555556


In [6]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets

def CreateDataFrame(N):
 columns = ['a','b','c','y']
 df = pd.DataFrame(columns=columns)
 for i in range(N):
  a = np.random.randint(10)
  b = np.random.randint(20)
  c = np.random.randint(5)
  y = "normal"
  if((a+b+c)>25):
   y="high"
  elif((a+b+c)<12):
   y= "low"

  df.loc[i]= [a, b, c, y]
 return df

df = CreateDataFrame(200)
print(df.head())

X = df[["a","b","c"]]
Y = df[["y"]]

le=LabelEncoder()
y=le.fit_transform(Y)

print(Y.head())
print(y[0:5])

Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, random_state=0)

dtc = DecisionTreeClassifier(criterion="entropy", max_depth=3)
ada_model=AdaBoostClassifier(base_estimator=dtc, n_estimators=100)
ada_model=ada_model.fit(Xtrain,ytrain)
ytest_pred=ada_model.predict(Xtest)
print(ada_model.score(Xtest, ytest))
print(confusion_matrix(ytest, ytest_pred)) 

iris= datasets.load_iris()
X = iris.data
Y = iris.target

le=LabelEncoder()
y=le.fit_transform(Y)

Xtrain, Xtest, ytrain, ytest = train_test_split(X, y, random_state=0)

gnb = GaussianNB()
rf = RandomForestClassifier(n_estimators=10)

base_methods=[rf, gnb, dtc]
for bm  in base_methods:
 print("Method: ", bm)
 ada_model=AdaBoostClassifier(base_estimator=bm)
 ada_model=ada_model.fit(Xtrain,ytrain)
 ytest_pred=ada_model.predict(Xtest)
 print(ada_model.score(Xtest, ytest))
 print(confusion_matrix(ytest, ytest_pred)) 

   a   b  c       y
0  2   7  2     low
1  7  10  0  normal
2  1   0  1     low
3  7   4  2  normal
4  5   9  4  normal


C:\Software\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


        y
0     low
1  normal
2     low
3  normal
4  normal
[1 2 1 2 2]
0.88
[[ 1  0  1]
 [ 0 16  4]
 [ 1  0 27]]
Method:  RandomForestClassifier(n_estimators=10)
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
Method:  GaussianNB()
0.9473684210526315
[[13  0  0]
 [ 0 15  1]
 [ 0  1  8]]
Method:  DecisionTreeClassifier(criterion='entropy', max_depth=3)
0.9736842105263158
[[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
